### PR TITLE
Integration tests: Move from circleci to Github Actions (GHA).

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan <smahajan@roblox.com>

### CODE REVIEW

**Review by rhatdan — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@shishir-a412ed BTW Have you tried this against Podman?

**Comment by shishir-a412ed** [comment]
@rhatdan Just tried with `podman-3.4.0` based on [`this comment`](https://github.com/containers/docker-lvm-plugin/issues/98#issuecomment-804324955)

```
[root@fedora33 loopback]# rpm -q podman
podman-3.4.0-0.10.rc2.fc33.x86_64
```

Getting this:

```
[root@fedora33 loopback]# podman volume create --driver lvm --opt size=0.2G foobar
Error: volume foobar uses volume plugin lvm but it could not be retrieved: no volume plugin with name lvm available: required plugin missing
```
How does `Podman` register external volume plugins?


```
[root@fedora33 loopback]# systemctl status docker-lvm-plugin
● docker-lvm-plugin.service - Docker Volume Driver for lvm volumes
     Loaded: loaded (/usr/lib/systemd/system/docker-lvm-plugin.service; disabled; vendor preset: disabled)
     Active: active (running) since Wed 2021-09-29 22:34:14 UTC; 31min ago
       Docs: man:docker-lvm-plugin(8)
   Main PID: 44494 (docker-lvm-plug)
      Tasks: 5 (limit: 2341)
     Memory: 6.6M
        CPU: 58ms
     CGroup: /system.slice/docker-lvm-plugin.service
             └─44494 /usr/libexec/docker/docker-lvm-plugin
```

**Comment by rhatdan** [comment]
@mheon PTAL ^^

**Comment by mheon** [comment]
We require they be listed in `containers.conf` in the `[engine.volume_plugins]` table - format is `plugin_name = "/path/to/plugin/socket"`

**Pull request merged**
