### PR TITLE
Small fixes to README

### PR DESCRIPTION
**Pull request by guzalv**

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
@guzalv Any specific reason you wan’t to change from SSH to HTTPS ? Both protocols are supported for ‘git clone’.

**Comment by guzalv** [comment]
@shishir-a412ed Just so that it is more straightforward to get started. With SSH, one needs to have their SSH public key added to GitHub as far as I know. Here is a trial in a fresh machine:

    foo@bar:/ $ git clone git@github.com:projectatomic/docker-lvm-plugin.git
    Cloning into 'docker-lvm-plugin'...
    The authenticity of host 'github.com (140.82.118.3)' can't be established.
    RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
    Are you sure you want to continue connecting (yes/no)? yes
    Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

**Comment by shishir-a412ed** [comment]
@guzalv Most of the developers who interact with GitHub know how to setup SSH keys (N even if they don't, something good to learn). The benefits (not punching in the password everytime) definitely outweighs the small effort required to setup the SSH keys. Having said that, I am happy keep both. 

How about ?

`1) git clone git@github.com:projectatomic/docker-lvm-plugin.git (You can also use HTTPS to clone: git clone https://github.com/projectatomic/docker-lvm-plugin.git)`

**Comment by guzalv** [comment]
@shishir-a412ed Sure, I personally agree that using SSH is way better from almost all points of view. Only in cases like I had now, when I one-time-needed this in a brand new box which is not associated with my identity, and it refused to let me clone it.

But anyways I think that so far I have only seen the HTTPS clone instruction in READMEs, so I assumed it is a convention and wanted to fix it.

I think what you suggested is a good tradeoff though, so I'll do that instead.

**Pull request merged**
